version: '3.8'

services:
  gps-service:
    build: .
    ports:
      - "3000:3000"
      - "9090:9090"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BATCH_INTERVAL=10000
      - BATCH_MAX_SIZE=100
      - QUEUE_CONCURRENCY=5
      - CLEANUP_ENABLED=true
      - METRICS_ENABLED=true
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3